// This file is auto-generated by ~/scripts/icons.mjs
import type {
  LucideIcon,
  LucideProps,
} from 'lucide-react-native'

import {
  BanknoteArrowDown,
  BanknoteArrowUp,
  BellRing,
  Book,
  BookPlus,
  Calendar,
  Calendar1,
  CalendarClock,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleDollarSign,
  CirclePlus,
  Clock,
  DollarSign,
  Home,
  ListTodo,
  MapPin,
  Menu,
  Mic,
  Minus,
  NotepadText,
  Pencil,
  Plus,
  RotateCcw,
  Settings,
  Smile,
  Square,
  SquareDashed,
  SunMoon,
  Timer,
  Trash,
  UserRoundCog,
  Wallet,
  X,
} from 'lucide-react-native'
import { cssInterop } from 'nativewind'
import { memo, useContext } from 'react'

import { TextClassContext } from '~/components/ui/text'

import { cn } from '~/lib/utils'

function iconWithClassName(icon: LucideIcon) {
  cssInterop(icon, {
    className: {
      target: 'style',
      nativeStyleToProp: {
        color: true,
        opacity: true,
        width: true,
        height: true,
      },
    },
  })
}

function createIcon(OriginalIcon: LucideIcon): LucideIcon {
  iconWithClassName(OriginalIcon)

  const Comp = memo(({ className, ...props }: LucideProps) => {
    const textClass = useContext(TextClassContext)
    return <OriginalIcon {...props} className={cn('text-foreground', textClass, className)} />
  })

  Comp.displayName = OriginalIcon.displayName

  return Comp
}

export const BanknoteArrowDownIcon = createIcon(BanknoteArrowDown)
export const BanknoteArrowUpIcon = createIcon(BanknoteArrowUp)
export const BellRingIcon = createIcon(BellRing)
export const BookIcon = createIcon(Book)
export const BookPlusIcon = createIcon(BookPlus)
export const CalendarIcon = createIcon(Calendar)
export const Calendar1Icon = createIcon(Calendar1)
export const CalendarClockIcon = createIcon(CalendarClock)
export const CheckIcon = createIcon(Check)
export const ChevronLeftIcon = createIcon(ChevronLeft)
export const ChevronRightIcon = createIcon(ChevronRight)
export const ChevronsUpDownIcon = createIcon(ChevronsUpDown)
export const CircleDollarSignIcon = createIcon(CircleDollarSign)
export const CirclePlusIcon = createIcon(CirclePlus)
export const ClockIcon = createIcon(Clock)
export const DollarSignIcon = createIcon(DollarSign)
export const HomeIcon = createIcon(Home)
export const ListTodoIcon = createIcon(ListTodo)
export const MapPinIcon = createIcon(MapPin)
export const MenuIcon = createIcon(Menu)
export const MicIcon = createIcon(Mic)
export const MinusIcon = createIcon(Minus)
export const NotepadTextIcon = createIcon(NotepadText)
export const PencilIcon = createIcon(Pencil)
export const PlusIcon = createIcon(Plus)
export const RotateCcwIcon = createIcon(RotateCcw)
export const SettingsIcon = createIcon(Settings)
export const SmileIcon = createIcon(Smile)
export const SquareIcon = createIcon(Square)
export const SquareDashedIcon = createIcon(SquareDashed)
export const SunMoonIcon = createIcon(SunMoon)
export const TimerIcon = createIcon(Timer)
export const TrashIcon = createIcon(Trash)
export const UserRoundCogIcon = createIcon(UserRoundCog)
export const WalletIcon = createIcon(Wallet)
export const XIcon = createIcon(X)
