// This file is auto-generated by ~/scripts/icons.mjs
import type {
  LucideIcon,
  LucideProps,
} from 'lucide-react-native'
import type { FC } from 'react'

import {
  BanknoteArrowDown,
  BanknoteArrowUp,
  BookPlus,
  Calendar,
  CalendarClock,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  DollarSign,
  Home,
  ListTodo,
  MapPin,
  Menu,
  Mic,
  Plus,
  RotateCcw,
  Settings,
  Smile,
  Square,
  SquareDashed,
  SunMoon,
  Trash,
  Wallet,
  X,
} from 'lucide-react-native'
import { cssInterop } from 'nativewind'
import { useContext } from 'react'

import { TextClassContext } from '~/components/ui/text'

import { cn } from '~/lib/utils'

function iconWithClassName(icon: LucideIcon) {
  cssInterop(icon, {
    className: {
      target: 'style',
      nativeStyleToProp: {
        color: true,
        opacity: true,
        width: true,
        height: true,
      },
    },
  })
}

function createIcon(OriginalIcon: LucideIcon): FC<LucideProps> {
  iconWithClassName(OriginalIcon)

  function Comp({ className, ...props }: LucideProps) {
    const textClass = useContext(TextClassContext)
    return <OriginalIcon {...props} className={cn('text-foreground', textClass, className)} />
  }

  Comp.displayName = OriginalIcon.displayName

  return Comp
}

export const BanknoteArrowDownIcon = createIcon(BanknoteArrowDown)
export const BanknoteArrowUpIcon = createIcon(BanknoteArrowUp)
export const BookPlusIcon = createIcon(BookPlus)
export const CalendarIcon = createIcon(Calendar)
export const CalendarClockIcon = createIcon(CalendarClock)
export const CheckIcon = createIcon(Check)
export const ChevronLeftIcon = createIcon(ChevronLeft)
export const ChevronRightIcon = createIcon(ChevronRight)
export const ChevronsUpDownIcon = createIcon(ChevronsUpDown)
export const ClockIcon = createIcon(Clock)
export const DollarSignIcon = createIcon(DollarSign)
export const HomeIcon = createIcon(Home)
export const ListTodoIcon = createIcon(ListTodo)
export const MapPinIcon = createIcon(MapPin)
export const MenuIcon = createIcon(Menu)
export const MicIcon = createIcon(Mic)
export const PlusIcon = createIcon(Plus)
export const RotateCcwIcon = createIcon(RotateCcw)
export const SettingsIcon = createIcon(Settings)
export const SmileIcon = createIcon(Smile)
export const SquareIcon = createIcon(Square)
export const SquareDashedIcon = createIcon(SquareDashed)
export const SunMoonIcon = createIcon(SunMoon)
export const TrashIcon = createIcon(Trash)
export const WalletIcon = createIcon(Wallet)
export const XIcon = createIcon(X)
