import { writeFileSync } from 'node:fs'

// @keep-sorted
// @keep-unique
const ICON_NAMES = [
  // 'Banknote',
  'BanknoteArrowDown',
  'BanknoteArrowUp',
  'Book',
  'BookPlus',
  'Calendar',
  'CalendarClock',
  'Check',
  'ChevronLeft',
  'ChevronRight',
  'ChevronsUpDown',
  'CircleDollarSign',
  'CirclePlus',
  'Clock',
  'DollarSign',
  'Home',
  'ListTodo',
  'MapPin',
  'Menu',
  'Mic',
  'Pencil',
  'Plus',
  'RotateCcw',
  'Settings',
  'Smile',
  'Square',
  'SquareDashed',
  'SunMoon',
  'Trash',
  'Wallet',
  'X',
]

function template(icons) {
  const template = `\
// This file is auto-generated by ~/scripts/icons.mjs
import type {
  LucideIcon,
  LucideProps,
} from 'lucide-react-native'

import {
${icons.map(x => `  ${x},`).join('\n')}
} from 'lucide-react-native'
import { cssInterop } from 'nativewind'
import { memo, useContext } from 'react'

import { TextClassContext } from '~/components/ui/text'

import { cn } from '~/lib/utils'

function iconWithClassName(icon: LucideIcon) {
  cssInterop(icon, {
    className: {
      target: 'style',
      nativeStyleToProp: {
        color: true,
        opacity: true,
        width: true,
        height: true,
      },
    },
  })
}

function createIcon(OriginalIcon: LucideIcon): LucideIcon {
  iconWithClassName(OriginalIcon)

  const Comp = memo(({ className, ...props }: LucideProps) => {
    const textClass = useContext(TextClassContext)
    return <OriginalIcon {...props} className={cn('text-foreground', textClass, className)} />
  })

  Comp.displayName = OriginalIcon.displayName

  return Comp
}

${
  icons
    .map((icon) => {
      return `export const ${icon}Icon = createIcon(${icon})`
    })
    .join('\n')
}
`

  return template
}

function main(outdir = './lib/icons.tsx', icons = ICON_NAMES) {
  const content = template(icons)
  writeFileSync(outdir, content)
}

main()
